kidzy_api_homepage:
    path:     /
    defaults: { _controller: KidzyApiBundle:Default:index }
allpacks:
    path: /packs/all
    defaults: {_controller: KidzyApiBundle:Pricing:allPack}
findpack:
    path: /packs/find/{id}
    defaults: {_controller: KidzyApiBundle:Pricing:findPack}
allfactures:
    path: /factures/all
    defaults: {_controller: KidzyApiBundle:Pricing:allFacture}
findfacture:
    path: /factures/find/{id}
    defaults: {_controller: KidzyApiBundle:Pricing:findFacture}
create_facture:
    path: /factures/new
    defaults: {_controller: KidzyApiBundle:Pricing:newFactureAction}
create222_facture:
    path: /factures/create/new/{idpack}/{iduser}/{idEnfant}/{prix}/{due}
    defaults: {_controller: KidzyApiBundle:Pricing:createnewFacture}
findparentpricing:
    path: /packs/parent/find/{id}
    defaults: {_controller: KidzyApiBundle:Pricing:finduserpr}
findfacturebyenfant:
    path: /factures/enfant/find/{id}
    defaults: {_controller: KidzyApiBundle:Pricing:findfacturebyenfant}
updatefacture:
    path: /factures/update/{id}/{paydate}
    defaults: {_controller: KidzyApiBundle:Pricing:updatefacture}