avis_index:
    path:     admin/
    defaults: { _controller: "KidzyBundle:Avis:index" }
    methods:  GET

avis_show:
    path:     admin/{idAvis}/show
    defaults: { _controller: "KidzyBundle:Avis:show" }
    methods:  GET

avis_new:
    path:     admin/new
    defaults: { _controller: "KidzyBundle:Avis:new" }
    methods:  [GET, POST]

avis_edit:
    path:     admin/{idAvis}/edit
    defaults: { _controller: "KidzyBundle:Avis:edit" }
    methods:  [GET, POST]

avis_delete:
    path:     admin/{idAvis}/delete
    defaults: { _controller: "KidzyBundle:Avis:delete" }
    methods:  DELETE

avisF:
    path:     /avisF
    defaults: { _controller: "KidzyBundle:Avis:avisF" }


Mesavis:
    path:     /Mesavis
    defaults: { _controller: "KidzyBundle:Avis:Mesavis" }

avis_supprimer:
    path:     /{idAvis}/supprimer
    defaults: { _controller: "KidzyBundle:Avis:supprimer" }
allAvis:
    path:     /allAvis
    defaults: { _controller: "KidzyBundle:Avis:allAvis" }

MesAvisMobile:
    path:     /MesAvisMobile/{idParent}
    defaults: { _controller: "KidzyBundle:Avis:MesAvisMobile" }

updateAvisMobile:
    path:     /updateAvisMobile/{idAvis}
    defaults: { _controller: "KidzyBundle:Avis:updateAvisMobile" }

ajoutAvis:
    path:     /ajoutAvis
    defaults: { _controller: "KidzyBundle:Avis:ajoutAvis" }

suppAvis:
    path:     /suppAvis/{idAvis}
    defaults: { _controller: "KidzyBundle:Avis:suppAvis" }

getUser:
    path:     /Avis/{idParent}
    defaults: { _controller: "KidzyBundle:Avis:getuser" }


