club:
    path:     /affichage
    defaults: { _controller: KidzyBundle:Club:index}
clubParent:
    path:     /liste
    defaults: { _controller: KidzyBundle:Club:indexParent}
clubindexFront:
    path:     /listes
    defaults: { _controller: KidzyBundle:Club:indexClub}
club_new:
    path:   admin/new
    defaults: { _controller: KidzyBundle:Club:new }
    methods:  [GET, POST]
club_show:
    path:     admin/{idClub}/show
    defaults: { _controller: KidzyBundle:Club:show }
    methods:  GET
club_delete:
    path:     admin/{idClub}/delete
    defaults: { _controller: KidzyBundle:Club:delete }
    methods:  DELETE
club_edit:
    path:     admin/{idClub}/edit
    defaults: { _controller: KidzyBundle:Club:edit }
    methods:  [GET, POST]
club_showEvent:
    path:     front/{idClub}/showEvent
    defaults: { _controller: KidzyBundle:Club:showEvent }
    methods:  GET
club_charts:
    path:     admin/charts
    defaults: { _controller: KidzyBundle:Club:charts }
    methods:  GET
print_club:
    path:     front/{idEnfant}/{idInscrit}/{idClub}/print
    defaults: { _controller: KidzyBundle:Club:print }
    methods:  GET
club_all:
    path:     /all/
    defaults: { _controller: KidzyBundle:Club:allClub }
club_all_mobile:
    path:     /MesClubs/{idParent}
    defaults: { _controller: KidzyBundle:Club:indexParentMobile }
club_details_mobile:
    path:     /Details/{idInscrit}/{idClub}/{idEnfant}
    defaults: { _controller: KidzyBundle:Club:showParentMobile }
club_Autre_mobile:
    path:     /AutresClubs/
    defaults: { _controller: KidzyBundle:Club:indexAutreMobile }
club_deleteMobile:
    path:     Quitter/{idInscrit}/
    defaults: { _controller: KidzyBundle:Club:deleteMobile }
Enfant_Mobile:
    path:    enfant/{idParent}/
    defaults: { _controller: KidzyBundle:Club:EnfantMobile }
New_Mobile:
    path:    New
    defaults: { _controller: KidzyBundle:Club:InsertMobile }
StatMobile:
    path:    stat
    defaults: { _controller: KidzyBundle:Club:StatMobile }
PrintMobile:
    path:    print/{idInscrit}/{idClub}/{idEnfant}
    defaults: { _controller: KidzyBundle:Club:printMobile }